name: untitled4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  autocomplete_textfield: ^2.0.1
  awesome_dialog: ^3.1.0
  badges: ^3.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.14
  flutter_native_splash: ^2.3.5
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  jiffy: ^5.0.1
  provider: ^6.0.5
  restart_app: ^1.2.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
